### ISSUE TITLE
io.jsonwebtoken.SignatureException原因分析

### ISSUE THREAD

**Issue by nickwongwong** [izhaorui/applelogin#1]
一部分成功，一部分失败；报错如下：
`io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.`

苹果官方会返回多个key，**原作者默认的取第一个，其实是有问题**
需要通过identityToken中第一部分header的kid，取匹配一个具体的key

核心代码
```
    String jwtKid = getKid(jwt);
    for (Keys key : appleKeys.keys) {
      if (StringUtils.equals(key.getKid(), jwtKid)) {
        // 注意获得kid匹配的key
        n = key.getN();
        ee = key.getE();
        logger.info(String.format("[苹果登录日志]jwt:%s,aud:%s,sub:%s", jwt, aud, sub));
        break;
      }
    }
```

参考：

**Comment by izhaorui** [comment]
嗯，这个已经解决了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "izhaorui/AppleLogin-java"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 晚上9:48
收件人:&nbsp;"izhaorui/AppleLogin-java"<AppleLogin-java@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[izhaorui/AppleLogin-java] io.jsonwebtoken.SignatureException原因分析 (#1)





 
一部分成功，一部分失败；报错如下：
 io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted.
 
苹果官方会返回多个key，原作者默认的取第一个，其实是有问题
 需要通过identityToken中第一部分header的kid，取匹配一个具体的key
 
核心代码
     String jwtKid = getKid(jwt);     for (Keys key : appleKeys.keys) {       if (StringUtils.equals(key.getKid(), jwtKid)) {         // 注意获得kid匹配的key         n = key.getN();         ee = key.getE();         logger.info(String.format("[苹果登录日志]jwt:%s,aud:%s,sub:%s", jwt, aud, sub));         break;       }     }  
参考：

**Comment by jonenet** [comment]
String jwtKid = getKid(jwt);
请问这个方法是什么？

**Comment by izhaorui** [comment]
很久了，忘记了。现在已经没用Java写了，改用.NetCore了
